In [4]:
# Exercise Set 1

import pandas as pd

data = {
"Name": [
    "Alice", "Bob", "Charlie", "David", "Evelyn",
    "Frank", "Grace", "Henry", "Isla", "Jack",
    "Karen", "Leo", "Mia", "Noah", "Olivia",
    "Paul", "Quinn", "Ruby", "Sam", "Tina"
],
"Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
"Department": [
    "HR", "Engineering", "Sales", "Marketing", "Engineering",
    "Finance", "Support", "Operations", "HR", "Sales",
    "Engineering", "Support", "Marketing", "Finance", "Operations",
    "Engineering", "HR", "Sales", "Support", "Marketing"
],
"Salary": [
    50000, 75000, 62000, 58000, 80000,
    54000, 52000, 70000, 51000, 64000,
    82000, 53000, 60000, 56000, 68000,
    79000, 49500, 65500, 54500, 61000
],
}

df = pd.DataFrame(data)

In [5]:
# Exercise 1
df.head()

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000
3    David   29    Marketing   58000
4   Evelyn   41  Engineering   80000

In [6]:
# Exercise 2
df.tail()

     Name  Age   Department  Salary
15   Paul   42  Engineering   79000
16  Quinn   24           HR   49500
17   Ruby   38        Sales   65500
18    Sam   35      Support   54500
19   Tina   29    Marketing   61000

In [7]:
# Exercise 3
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        20 non-null     str
 1   Age         20 non-null     int64
 2   Department  20 non-null     str
 3   Salary      20 non-null     int64
dtypes: int64(2), str(2)
memory usage: 772.0 bytes

In [8]:
# Exercise 4
df.shape

(20, 4)

In [9]:
# Exercise Set 2
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print(df.head(11))

    PassengerId  Survived  Pclass  \
0             1         0       3
1             2         1       1
2             3         1       3
3             4         1       1
4             5         0       3
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss. Laina  female  26.0      0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
5                                    Moran, Mr. James    male   NaN      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master. Gosta Leonard    male   2.0      3
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1

    Parch            Ticket     Fare Cabin Embarked
0       0         A/5 21171   7.2500   NaN        S
1       0          PC 17599  71.2833   C85        C
2       0  STON/O2. 3101282   7.9250   NaN        S
3       0            113803  53.1000  C123        S
4       0            373450   8.0500   NaN        S
5       0            330877   8.4583   NaN        Q
6       0             17463  51.8625   E46        S
7       1            349909  21.0750   NaN        S
8       2            347742  11.1333   NaN        S
9       0            237736  30.0708   NaN        C
10      1           PP 9549  16.7000    G6        S

In [10]:
# Exercise 1
df.loc[12,['Name','Age']]

Name    Saundercock, Mr. William Henry
Age                               20.0
Name: 12, dtype: object

In [11]:
# Exercise 2
df.iloc[0:5, 0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

In [12]:
# Exercise 3
df.loc[(df['Pclass'] == 1) & (df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [13]:
# Exercise 4
df.iloc[9,5]

np.float64(14.0)

In [14]:
# Exercise 5
df.loc[100:105,['Fare','Survived']]

        Fare  Survived
100   7.8958         0
101   7.8958         0
102  77.2875         0
103   8.6542         0
104   7.9250         0
105   7.8958         0

In [15]:
# Exercise Set 3
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
# Exercise 1
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [17]:
# Exercise 2
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [18]:
# Exercise 3
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [19]:
# Exercise 4
df['Age'].mean()

np.float64(29.69911764705882)

In [20]:
#Exercise 5
df['Fare'].max()

np.float64(512.3292)

In [21]:
# Exercise 6
df['Name'].nunique()

891

In [22]:
# Exercise 7
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [23]:
# Exercise 8
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [24]:
# Exercise Set 1

import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

In [25]:
df

      Name  Age     City          Email
0    Alice   25      NYC  a@example.com
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com
3    David   40    Miami  d@example.com

In [26]:
# Exercise 1
df = df.drop('Email', axis=1)
df

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40    Miami

In [27]:
# Exercise 2
df = df.drop(2, axis=0)
df

    Name  Age   City
0  Alice   25    NYC
1    Bob   30     LA
3  David   40  Miami

In [28]:
# Exercise 3
df = df.drop(['City', 'Email'], axis=1)
df

KeyError: "['Email'] not found in axis"

In [ ]:
# Exercise 4
df = df.drop(df.head(1).index, axis=0)
df = df.drop(df.tail(1).index, axis=0)
df

In [ ]:
# Exercise Set 2

import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

In [ ]:
# Exercise 1

df.head()

In [ ]:
# Exercise 2

df.isnull()

In [ ]:
# Exercise 3

df.isnull().sum()

In [ ]:
# Exercise 4

df.dropna()

In [ ]:
# Exercise 6

df.dropna(axis=1)

In [ ]:
# Exercise 8

df.fillna(df['Age'].mean())

In [ ]:
# Exercise 9

df.fillna('Unknown')

df

In [ ]:
# Exercise Set 3

import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
# Exercise 1

df.duplicated()

In [ ]:
# Exercise 2

df_cleaned = df.drop_duplicates()

df_cleaned

In [ ]:
# Exercise 3
df_cleaned = df.drop_duplicates(keep='last')
df_cleaned

In [ ]:
# Exercise 4

df_cleaned = df.drop_duplicates(keep=False)
df_cleaned

In [ ]:
# Exercise Set 1

import pandas as pd

data = {
"fname": ["Alice", "Bob", "Charlie"],
"lname": ["Smith", "Jones", "Brown"],
"ctry": ["USA", "Canada", "UK"],
}

df = pd.DataFrame(data)

In [ ]:
# Exercise 1

df.rename(columns={
    'fname': 'FirstName',
    'lname': 'LastName'
})

In [ ]:
# Exercise 2
df.columns = ['FirstName', 'LastName', 'Country']

df

In [29]:
# Exercise Set 2

import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)

df

      Name     Dept    Sal
0    Alice       HR  60000
1      Bob  Finance  70000
2  Charlie       IT  80000

In [33]:
# Exercise 1

df.rename(columns={
    'Dept': 'Department',
    'Sal': 'Salary'
})

      Name Department  Salary
0    Alice         HR   60000
1      Bob    Finance   70000
2  Charlie         IT   80000

In [31]:
# Exercise 2

df = df['Salary', 'Name', 'Department']
cols = df.columns.tolist()
new_order = [cols[-1]] + cols[:-1]  # Moves the last column to the front
df = df[new_order]

KeyError: ('Salary', 'Name', 'Department')

In [34]:
# Exercise 3

df

      Name     Dept    Sal
0    Alice       HR  60000
1      Bob  Finance  70000
2  Charlie       IT  80000

In [35]:
# Exercise Set 3

import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

In [43]:
# Exercise 1

df.groupby('Store')[['Sales', 'Profit']].agg('mean')

        Sales  Profit
Store
A       90.00   25.00
B      115.00   37.50
C       78.75   21.75

In [45]:
# Exercise 2
df.groupby('Product').agg({
    'Sales': 'max',
    'Profit': 'min'
})

         Sales  Profit
Product
Apples     120      30
Bananas    110      18
Oranges     80      15

In [47]:
# Exercise 3

df.groupby('Store').agg(
    Avg_Sales=('Sales', 'mean'),
    Max_Profit=('Profit', 'max')
)

       Avg_Sales  Max_Profit
Store
A          90.00          30
B         115.00          40
C          78.75          32

In [48]:
# Exercise 4 (Bonus)

df.groupby(['Store', 'Product'])['Sales'].sum()

Store  Product
A      Apples     100
       Bananas     90
       Oranges     80
B      Apples     120
       Bananas    110
C      Apples      95
       Bananas    160
       Oranges     60
Name: Sales, dtype: int64

In [49]:
# Exercise Set 4

import pandas as pd

df_customers = pd.DataFrame({
"CustomerName": ["Alice", "Bob", "Charlie"]
}, index=[101, 102, 103])

df_orders = pd.DataFrame({
"OrderTotal": [250, 300, 400]
}, index=[101, 102, 103])

In [51]:
# Exercise 1

result = df_customers.join(df_orders)
print(result)

    CustomerName  OrderTotal
101        Alice         250
102          Bob         300
103      Charlie         400

In [52]:
# Exercise 2

df_cities = pd.DataFrame({
    'City': ['NYC', 'LA', 'Chicago']
}, index=[101, 102, 103])

result = df_customers.join(df_cities)
print(result)

    CustomerName     City
101        Alice      NYC
102          Bob       LA
103      Charlie  Chicago